services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
    ports:
      - "55432:5432" # для доступа с хоста (DBeaver/psql)
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: chat
      DB_PASSWORD: chat
      DB_NAME: chat

volumes:
  pgdata: